server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance_kb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
  
  data:
    redis:
      host: localhost
      port: 6379

